version: '3.1'

services:

  redis:
    container_name: my_redis_container
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - elastic 

networks:
  elastic:
    driver: bridge

